postgresql:
  image: postgres:latest

project:
  build: ./
  command: python -u main.py
  volumes:
    - ./dialogs
    - ./resources
    - ./venv
  depends_on:
    - postgresql
  links:
    - postgresql
